CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE "bank_details" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "CUST_ID" INTEGER NOT NULL,
    "ACCOUNT_NUMBER" TEXT,
    "SORT_CODE" TEXT,
    FOREIGN KEY(CUST_ID) REFERENCES customers(ID)
);
CREATE TABLE personal_details (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "CUST_ID" INTEGER NOT NULL,
    "FIRST_NAME" TEXT,
    "SURNAME" TEXT,
    "ADDRESS_LINE_1" TEXT,
    "ADDRESS_LINE_2" TEXT,
    "TOWN" TEXT,
    "POSTCODE" TEXT,
    "EMAIL" TEXT,
    FOREIGN KEY(CUST_ID) REFERENCES customers(ID)
);
CREATE TABLE "customers" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "USERNAME" TEXT UNIQUE NOT NULL,
    "ACTIVE" CHAR NOT NULL
);
;
